GRANT ALL PRIVILEGES ON DATABASE ebgeo_backend TO user_ebgeo2;
GRANT ALL ON SCHEMA ng TO user_ebgeo2;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ng TO user_ebgeo2;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ng TO user_ebgeo2;